### ISSUE TITLE
Pxt findet Modul-Metadaten nicht

### ISSUE THREAD

**Issue by ghost** [mcnoil/pxt-test#2]
... wegen unpassend benannter Datei pxt.json.

Vorschlag (ohne eigenen Issue):
Verschiedene Module nicht in verschiedene Repositories, sondern in verschiedene Verzeichnisse im gleichen Repo. Statt pxttest/ und pxt-dingssensor/ lieber pxt/testmodul/ und pxt/dingssensor/.

**Comment by ghost** [comment]
@mcnoil

**Comment by mcnoil** [comment]
die entsprechede datei heißt in allen Modulen in allen beispielen, die ich mir angeschaut habe pxt.json.
Ich bin mir nicht sicher, wo man den entsprechenden Namen anders angeben könnte.
Dieses Repo werde ich vermutlich sogar vollständig löschen, sobald  ich damit herrausgefunden habe, was ich möchte.
ob mehrere Module in einem Repo überhaupt möglich ist weiß ich gerade nicht. Wahrscheinlich schon, aber wahrscheinlich muß man dafür auch besser wissen, wie man entsprechendes Einbindet.
Aus den beispielen, die ich mir bisher angeschaut habe konnte ich das jedenfalls nicht erschließen.

**Comment by ghost** [comment]
Genau, sie soll "pxt.json" heißen, nicht "pxt.jason", wie Du sie benannt hattest. Weiß die Syntax nicht, um hier auf einen Commit zu verweisen, aber ich habe die Umbenennung erledigt mit dem Commit
[master 6eeb6e5] Renamed pxt.jason as pxt.json
Ich bekomme Mails, wenn Du die von mir eröffneten Issues kommentierst. Bekommst Du auch diesen Kommentar als Mail? Schließe Issue #2.
